name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://npm.yourcompany.com/'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run quality checks
        run: npm run quality-check
        
      - name: Build library
        run: npm run build:lib
        
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub release comment
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
            });
            
            await github.rest.repos.createReleaseComment({
              owner: context.repo.owner,
              repo: context.repo.repo, 
              release_id: release.id,
              body: `📦 Package published to internal NPM registry!\n\nInstall with:\n\`\`\`bash\nnpm install ${context.payload.release.tag_name}\n\`\`\``
            });